# Kismet Network Monitoring Module
# Configures Kismet with customizable settings for sensor deployment

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.kismet-sensor;

  # Default Kismet configuration with common settings
  kismetSiteConf = pkgs.writeText "kismet_site.conf" ''
    # Kismet Site Configuration
    # Generated by NixOS module - Edit module options to customize

    # ========================================
    # Logging Configuration
    # ========================================

    # Log to the specified directory
    log_prefix=/var/lib/kismet/logs/

    # Log types
    log_types=kismet

    # Keep logs for 7 days
    log_title=sensor-%Y-%m-%d-%H-%M-%S

    # ========================================
    # Network Interfaces
    # ========================================

    # Example WiFi monitoring interface (uncomment and modify as needed)
    # source=wlan0:type=linuxwifi,hop=true,hop_channels="1,6,11"
    ${concatStringsSep "\n" (map (iface: "source=${iface}") cfg.interfaces)}

    # Example for specific WiFi adapter
    # source=wlan1:type=linuxwifi,hop=true,hop_channels="1,2,3,4,5,6,7,8,9,10,11,12,13"
    source=wlp1s0u1u3:type=linuxwifi,hop=true
    source=wlp1s0u1u2:type=linuxwifi,hop=true
    source=wlp1s0u1u1:type=linuxwifi,hop=true
    source=wlp1s0u1u4:type=linuxwifi,hop=true
    # Example for RTL-SDR
    # source=rtl433-0:type=rtl433,device=0

    # ========================================
    # GPS Configuration
    # ========================================

    # GPS support (if gpsd is running)
    gps=${if cfg.gps.enable then "true" else "false"}

    # GPSD host and port
    ${optionalString cfg.gps.enable ''
    gpshost=${cfg.gps.host}
    gpsport=${toString cfg.gps.port}
    ''}

    # GPS reconnect automatically
    ${optionalString cfg.gps.enable ''
    gpsreconnect=true
    ''}

    # ========================================
    # Web UI Configuration
    # ========================================

    # HTTP server settings
    httpd_bind_address=${cfg.httpd.bindAddress}
    httpd_port=${toString cfg.httpd.port}

    # Allow connections from any host (be careful with this in production)
    httpd_allowed_hosts=${cfg.httpd.allowedHosts}

    # Web UI username and password (change these!)
    httpd_username=${cfg.httpd.username}
    httpd_password=${cfg.httpd.password}

    # Session timeout (in seconds)
    httpd_session_timeout=7200

    # ========================================
    # Data Storage Configuration
    # ========================================

    # Keep only the most recent N devices in memory
    tracker_device_timeout=300

    # Maximum number of devices to track
    tracker_max_devices=10000

    # Database settings
    kis_log_devices=true
    kis_log_datasources=true

    # ========================================
    # Alert Configuration
    # ========================================

    # Example alerts (uncomment and modify as needed)
    # alert=APSPOOF,1/min,5/min,0/min
    # alert=CHANCHANGE,1/min,5/min,0/min
    # alert=BCASTDISCON,1/min,5/min,0/min
    # alert=AIRJACKSSID,1/min,5/min,0/min
    # alert=PROBENOJOIN,1/min,5/min,0/min
    # alert=DISCONCODEINVALID,1/min,5/min,0/min
    # alert=MALFORMMGMT,1/min,5/min,0/min
    # alert=LONGSSID,1/min,5/min,0/min

    # ========================================
    # Performance Tuning
    # ========================================

    # Number of threads for packet processing
    packet_dedup_size=2048

    # Packet buffer size
    packet_backlog_warning=512
    packet_backlog_limit=1024

    # ========================================
    # Custom User Settings
    # ========================================
    ${cfg.extraConfig}
  '';

in {
  options.services.kismet-sensor = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = "Enable Kismet network monitoring";
    };

    interfaces = mkOption {
      type = types.listOf types.str;
      default = [];
      example = [ "wlan0:type=linuxwifi" "wlan1:type=linuxwifi,hop=true" ];
      description = "Network interfaces to monitor";
    };

    gps = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable GPS support via gpsd";
      };

      host = mkOption {
        type = types.str;
        default = "127.0.0.1";
        description = "GPSD host";
      };

      port = mkOption {
        type = types.port;
        default = 2947;
        description = "GPSD port";
      };
    };

    httpd = {
      bindAddress = mkOption {
        type = types.str;
        default = "0.0.0.0";
        description = "HTTP server bind address";
      };

      port = mkOption {
        type = types.port;
        default = 2501;
        description = "HTTP server port";
      };

      allowedHosts = mkOption {
        type = types.str;
        default = "*";
        description = "Allowed hosts for HTTP connections";
      };

      username = mkOption {
        type = types.str;
        default = "kismet";
        description = "Web UI username";
      };

      password = mkOption {
        type = types.str;
        default = "changeme";
        description = "Web UI password";
      };
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      example = ''
        # Additional custom configuration
        source=rtl433-0:type=rtl433,device=0
        alert=APSPOOF,1/min,5/min,0/min
      '';
      description = "Extra configuration to append to kismet_site.conf";
    };

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/kismet";
      description = "Directory for Kismet data and logs";
    };
  };

  config = mkIf cfg.enable {
    # Install Kismet and related packages
    environment.systemPackages = with pkgs; [
      kismet
      aircrack-ng
      hcxdumptool
      hcxtools
      tcpdump
      wireshark-cli
      gpsd  # GPS daemon
      (python3.withPackages (ps: with ps; [ gps3 ]))  # GPS Python tools
    ];

    # Kismet service
    systemd.services.kismet = {
      description = "Kismet Wireless Network Detector";
      after = [ "network.target" ];
      wantedBy = [ "multi-user.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.kismet}/bin/kismet --no-console-wrapper -c ${kismetSiteConf} -t sensor";
        Restart = "always";
        RestartSec = "10s";

        # Run as root for interface access
        User = "root";
        Group = "root";

        # Working directory
        WorkingDirectory = cfg.dataDir;

        # Create required directories
        RuntimeDirectory = "kismet";
        StateDirectory = "kismet";
        LogsDirectory = "kismet";
      };

      preStart = ''
        # Ensure data directories exist
        mkdir -p ${cfg.dataDir}/logs
        mkdir -p ${cfg.dataDir}/data

        # Set interface to monitor mode if specified
        ${concatStringsSep "\n" (map (iface:
          let
            ifaceName = head (splitString ":" iface);
          in ''
            # Check if ${ifaceName} exists and set to monitor mode
            if ${pkgs.iproute2}/bin/ip link show ${ifaceName} >/dev/null 2>&1; then
              echo "Preparing interface ${ifaceName} for monitoring..."
              ${pkgs.iw}/bin/iw ${ifaceName} set type monitor || true
              ${pkgs.iproute2}/bin/ip link set ${ifaceName} up || true
            fi
          ''
        ) cfg.interfaces)}
      '';

      postStop = ''
        # Reset interfaces to managed mode
        ${concatStringsSep "\n" (map (iface:
          let
            ifaceName = head (splitString ":" iface);
          in ''
            if ${pkgs.iproute2}/bin/ip link show ${ifaceName} >/dev/null 2>&1; then
              echo "Resetting interface ${ifaceName}..."
              ${pkgs.iw}/bin/iw ${ifaceName} set type managed || true
            fi
          ''
        ) cfg.interfaces)}
      '';
    };

    # Open firewall ports for Kismet
    networking.firewall.allowedTCPPorts = [ cfg.httpd.port ];

    # Create Kismet data directory
    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir} 0750 root root -"
      "d ${cfg.dataDir}/logs 0750 root root -"
      "d ${cfg.dataDir}/data 0750 root root -"
    ];

    # GPS support is configured in configuration.nix when gps.enable = true
    # This avoids conflicts with the main gpsd service configuration
  };
}
